# Generated by Django 4.1.2 on 2022-10-17 15:25

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="pdf",
            field=models.FileField(
                null=True,
                upload_to="uploads/",
                validators=[base.validators.validate_file_extension],
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="writer",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
