# Generated by Django 4.1.2 on 2022-10-17 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_book_pdf_book_writer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book", options={"ordering": ["-date_posted"]},
        ),
        migrations.RemoveField(model_name="book", name="complete",),
        migrations.AddField(
            model_name="book",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
